### ISSUE TITLE
bug: Possible prob when listing virt envs

### ISSUE THREAD

**Issue by dpetka2001** [neolooong/whichpy.nvim#4]
Hi, I just read about your plugin on Reddit and thought I'd give it a try. I use `fish` shell and also `virtualfish` to manage my virtual envs. When I do `:WhichPy select` then it lists double items under `~/.virtualenvs` which is the location where the virtual envs are stored.

Here's a screenshot of what I'm getting (I'm using fzf-lua picker, but also happens with the builtin and telescope)

![2024-12-21_16-41](https://github.com/user-attachments/assets/79ae0f75-3554-4a28-9387-df8409544401)

**Comment by neolooong** [comment]
fixed.
thank you.

**Comment by dpetka2001** [comment]
@neolooong Just so that I don't open another issue, I also noticed that when I choose a virtual env from the `fzf-lua` picker, it doesn't seem to get activated. I checked with `:!python3 --version` from Neovim command line. With `venv-selector` whenever I did `:!python3 --version` after choosing a virtual env it showed the correct version of Python3 for the corresponding virtual env. In my screenshot above `test` venv is with python3.10 while `Mit` is with python3.12.

Another thing I noticed is that if I want to disable the locator with `opts.locator.enable = false` I get an error 
```lua
          Failed to run `config` for whichpy.nvim

...azyVimDev/lazy/whichpy.nvim/lua/whichpy/locator/init.lua:26: attempt to index local 'locator_opts' (a boolean value)

# stacktrace:
  - /whichpy.nvim/lua/whichpy/locator/init.lua:26 _in_ **setup_locator**
  - /whichpy.nvim/lua/whichpy/config.lua:87 _in_ **setup_config**
  - /whichpy.nvim/lua/whichpy/init.lua:7 _in_ **setup**
  - ~/.config/LazyVimDev/lua/config/lazy.lua:11
  - ~/.config/LazyVimDev/init.lua:24
```

**Comment by neolooong** [comment]
> it doesn't seem to get activated

Mmm... yes, whichpy doesn't activate venv. The purpose of plugin just want to make LSP work with specific interpreter.

`:!python3` don't use you selected is what I want. Imaging a situation, you select a venv which don't contain `pip` file. Then `:!pip install something` would messup your environ.

> disable the locator with `opts.locator.enable = false` I get an error

The correct way to disable locator is like this:
```lua
require("whichpy").setup({
  locator = {
    poetry = { enable = false },
    conda = { enable = false },
  }
})
```

**Comment by dpetka2001** [comment]
Ok, thanks for clarifying. I'm pretty new to programming myself and Python. 

Can you elaborate on the purpose of the plugin, because I don't exactly understand it? I thought it was for listing the virtual envs and be able to switch to one, but apparently I'm mistaken. What exactly do you mean when you say "The purpose of plugin just want to make LSP work with specific interpreter"?

**Comment by neolooong** [comment]
After selecting the interpreter path, Whichpy only updates the LSP configuration and notifies the LSP server. This plugin does not handle:

1. Using `:python` to execute code
2. Automatically activating virtual environments when opening terminals inside neovim
3. etc

**Comment by neolooong** [comment]
I add a new option `update_path_env`. Set it to `true` if you want to use `:!python`.
